Output assets/p5-docs.gif

Set Shell bash
Set FontFamily "JetBrains Mono"
Set FontSize 18
Set Width 1200
Set Height 800
Set TypingSpeed 300ms
Set PlaybackSpeed 1.0
Set Theme "Catppuccin Frappe"
Set Padding 20
Set WindowBar Colorful

Hide
Sleep 1s
Type "export TERM=xterm-256color"
Enter
Type "PS1='$ '"
Enter
Type "clear"
Enter
Sleep 500ms
Type "clear"
Enter
Show

Type "nvim"
Sleep 1s
Enter
Sleep 5s
Type ":P5 docs"
Sleep 500ms
Enter
Sleep 5s
Type ":q!"
Sleep 1s
Enter
Sleep 2s
