/**
 * p5.js Core Modules Index
 * 
 * This index provides access to all p5.js core modules.
 * Generated for p5.nvim plugin.
 * 
 * DO NOT EDIT - This file is automatically generated
 * Generated: 2026-02-04T04:02:04.680Z
 * Total modules: 0
 */

// Module exports organized by category
export const modules = {

};

// Get all available categories
export const getCategories = () => {
  return [];
};

// Get modules in a category
export const getCategoryModules = (category) => {
  return modules[category] || {};
};

// Convenience exports
export const loadModule = async (category, name) => {
  if (modules[category] && modules[category][name]) {
    return await modules[category][name]();
  }
  throw new Error(`Module ${category}.${name} not found. Available categories: ${getCategories().join(', ')}`);
};

// Load all modules in a category
export const loadCategory = async (category) => {
  const categoryModules = modules[category];
  if (!categoryModules) {
    throw new Error(`Category ${category} not found. Available categories: ${getCategories().join(', ')}`);
  }
  
  const results = {};
  for (const [name, loader] of Object.entries(categoryModules)) {
    results[name] = await loader();
  }
  return results;
};

// Load all core modules
export const loadAll = async () => {
  const results = {};
  for (const [category, categoryModules] of Object.entries(modules)) {
    results[category] = await loadCategory(category);
  }
  return results;
};

// Module information
export const moduleInfo = {
  totalModules: 0,
  categories: [],
  totalCategories: 0,
  generatedAt: '2026-02-04T04:02:04.680Z',
  modules: []
};

export default modules;
