-- Test suite for p5.nvim core functions
-- Run with: nvim --headless -u NONE -c "set rtp+=." -c "lua require('plenary.busted')" -c "BustedDirectory tests/ {minimal_init = '.nvimrc', sequential = true}"

local core = require("p5.core")

describe("p5.core", function()
  describe("file_exists", function()
    it("returns true for existing file", function()
      assert.is_true(core.file_exists("tests/core_spec.lua"))
    end)

    it("returns false for non-existing file", function()
      assert.is_false(core.file_exists("tests/non_existing_file.lua"))
    end)
  end)

  describe("dir_exists", function()
    it("returns true for existing directory", function()
      assert.is_true(core.dir_exists("tests"))
    end)

    it("returns false for non-existing directory", function()
      assert.is_false(core.dir_exists("tests/non_existing_dir"))
    end)
  end)

  describe("command_exists", function()
    it("returns true for existing command", function()
      assert.is_true(core.command_exists("ls"))
    end)

    it("returns false for non-existing command", function()
      assert.is_false(core.command_exists("nonexistent_command_12345"))
    end)
  end)

  describe("read_json_file", function()
    it("returns data for valid JSON file", function()
      local data, err = core.read_json_file("libs.json")
      assert.is_nil(err)
      assert.is_table(data)
    end)

    it("returns error for non-existing file", function()
      local data, err = core.read_json_file("nonexistent.json")
      assert.is_not_nil(err)
      assert.is_nil(data)
    end)
  end)

  describe("get_cache_dir", function()
    it("returns a valid cache directory path", function()
      local cache_dir = core.get_cache_dir()
      assert.is_string(cache_dir)
      assert.is_true(#cache_dir > 0)
    end)
  end)

  describe("get_cache_file", function()
    it("returns a valid cache file path", function()
      local cache_file = core.get_cache_file("test.json")
      assert.is_string(cache_file)
      assert.is_true(cache_file:match("test.json$"))
    end)
  end)

  describe("get_plugin_root", function()
    it("returns a valid plugin root path", function()
      local root = core.get_plugin_root()
      assert.is_string(root)
      assert.is_true(#root > 0)
    end)
  end)

  describe("get_asset_dir", function()
    it("returns a valid asset directory path", function()
      local asset_dir = core.get_asset_dir()
      assert.is_string(asset_dir)
      assert.is_true(asset_dir:match("assets$"))
    end)
  end)

  describe("generate_cache_key", function()
    it("returns a 16-character hex string", function()
      local key = core.generate_cache_key("https://example.com/file.js")
      assert.is_string(key)
      assert.equals(16, #key)
    end)

    it("returns same key for same URL", function()
      local key1 = core.generate_cache_key("https://example.com/file.js")
      local key2 = core.generate_cache_key("https://example.com/file.js")
      assert.equals(key1, key2)
    end)
  end)

  describe("is_cache_valid", function()
    it("returns true for existing cache file", function()
      local cache_dir = core.get_cache_dir()
      local test_file = cache_dir .. "/test_cache_file"
      vim.fn.writefile({"test"}, test_file)
      assert.is_true(core.is_cache_valid(test_file))
      vim.fn.delete(test_file)
    end)

    it("returns false for non-existing cache file", function()
      assert.is_false(core.is_cache_valid("/nonexistent/path/cache_file"))
    end)
  end)

  describe("split_commands", function()
    it("contains all expected positions", function()
      assert.is_table(core.split_commands.below)
      assert.is_table(core.split_commands.above)
      assert.is_table(core.split_commands.left)
      assert.is_table(core.split_commands.right)
    end)
  end)

  describe("server_configs", function()
    it("contains python config", function()
      assert.is_table(core.server_configs.python)
      assert.equals("python3", core.server_configs.python.check)
    end)
  end)
end)
