// Auto-generated by p5.nvim
function setup() {
  createCanvas(800, 600);
  background(220);
  // Your setup code here
}
function draw() {
  // Your draw code here
  // Example: Draw a circle that follows the mouse
  fill(255, 100, 100, 50);
  noStroke();
  circle(mouseX, mouseY, 50);
}
// Example interaction
function mousePressed() {
  console.log('Mouse pressed at:', mouseX, mouseY);
  background(random(100, 255), random(100, 255), random(100, 255));
}
